import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { DashboardShell } from "../components/DashboardShell";
import { SparklineChart } from "../components/SparklineChart";
import { SolarWorkingResultsPanel } from "../components/SolarWorkingResultsPanel";
import { UploadWorkbookPanel } from "../components/UploadWorkbookPanel";
import { WorkbookHistoryPanel } from "../components/WorkbookHistoryPanel";
import {
  fetchClientSummary,
  fetchWorkbookHistory,
  fetchWorkbookResults,
} from "../lib/api";
import { clearSession, getStoredSession } from "../lib/authStorage";
import type {
  PortalSummary,
  WorkbookListItem,
  WorkbookResultsResponse,
} from "../lib/types";


export function ClientDashboardPage() {
  const navigate = useNavigate();
  const [summary, setSummary] = useState<PortalSummary | null>(null);
  const [error, setError] = useState("");
  const [workbooks, setWorkbooks] = useState<WorkbookListItem[]>([]);
  const [selectedWorkbookId, setSelectedWorkbookId] = useState<string | null>(null);
  const [selectedResult, setSelectedResult] = useState<WorkbookResultsResponse | null>(
    null,
  );
  const [resultError, setResultError] = useState("");
  const [isLoadingResults, setIsLoadingResults] = useState(false);

  const selectedWorkbook = workbooks.find(
    (item) => item.workbook_id === selectedWorkbookId,
  );
  const latestRow = selectedResult?.rows[selectedResult.rows.length - 1];
  const totalBalance =
    selectedResult?.rows.reduce((sum, row) => sum + row.tneb_balance, 0) ?? 0;
  const balanceSeries = selectedResult?.rows.map((row) => row.tneb_balance) ?? [];
  const solarSeries = selectedResult?.rows.map((row) => row.solar_total) ?? [];
  const iexSeries = selectedResult?.rows.map((row) => row.iex_total) ?? [];
  const workbookRowSeries = workbooks.map((item) => item.solar_working_rows);

  const summaryCards = [
    {
      label: "Workbook Runs",
      value: String(workbooks.length),
      detail: "Uploaded calculation batches available for review.",
      series: workbookRowSeries,
      tone: "neutral" as const,
    },
    {
      label: "Selected Month",
      value: selectedResult?.workbook_month ?? selectedWorkbook?.workbook_month ?? "No data",
      detail: "Current workbook slice opened in the dashboard.",
      series: solarSeries,
      tone: "accent" as const,
    },
    {
      label: "Calculated Rows",
      value: String(selectedResult?.rows.length ?? 0),
      detail: "Daily Solar Working rows generated by the backend service.",
      series: iexSeries,
      tone: "neutral" as const,
    },
    {
      label: "Net Balance",
      value: totalBalance.toLocaleString(undefined, {
        maximumFractionDigits: 2,
        minimumFractionDigits: 2,
      }),
      detail: "Aggregate TNEB balance across the selected workbook.",
      series: balanceSeries,
      tone: totalBalance >= 0 ? ("accent" as const) : ("warning" as const),
    },
  ];

  useEffect(() => {
    const session = getStoredSession();
    if (!session) {
      navigate("/login/client", { replace: true });
      return;
    }

    fetchClientSummary(session.token)
      .then(setSummary)
      .catch((requestError: Error) => {
        setError(requestError.message);
      });

    fetchWorkbookHistory(session.token)
      .then((items) => {
        setWorkbooks(items);
        if (items.length > 0) {
          setSelectedWorkbookId(items[0].workbook_id);
        }
      })
      .catch((requestError: Error) => {
        setError((current) => current || requestError.message);
      });
  }, [navigate]);

  useEffect(() => {
    const session = getStoredSession();
    if (!session || !selectedWorkbookId) {
      return;
    }

    setResultError("");
    setIsLoadingResults(true);
    fetchWorkbookResults(session.token, selectedWorkbookId)
      .then(setSelectedResult)
      .catch((requestError: Error) => {
        setResultError(requestError.message);
      })
      .finally(() => {
        setIsLoadingResults(false);
      });
  }, [selectedWorkbookId]);

  return (
    <DashboardShell
      navItems={[
        { hint: "Active", isActive: true, label: "Workbook Command" },
        { hint: "Upload", label: "Ingestion Queue" },
        { hint: "Rows", label: "Solar Output" },
        { hint: "Tenant", label: "Access Scope" },
      ]}
      onSignOut={() => {
        clearSession();
        navigate("/", { replace: true });
      }}
      portalLabel="Client Portal"
      subtitle="Tenant-facing workbook upload, calculation review, and monthly Solar Working validation in one operational workspace."
      title="Workbook Upload And Solar Working Dashboard"
      topMeta={[
        {
          label: "Tenant",
          value: summary?.user.tenant_id ? "Assigned" : "Shared Demo",
        },
        {
          label: "Workbook",
          value: selectedWorkbook?.workbook_month ?? "Awaiting selection",
        },
        {
          label: "Latest Date",
          value: latestRow?.reading_date ?? "No rows yet",
        },
      ]}
      userEmail={summary?.user.email}
      userName={summary?.user.full_name}
    >
      <section className="dashboard-banner panel span-12">
        <div>
          <p className="eyebrow">Operations Snapshot</p>
          <h3>Daily energy workbook execution with direct result visibility.</h3>
          <p className="muted">
            Review uploads, validate generated rows, and inspect day-level TNEB,
            IEX, solar, and balance numbers without leaving the dashboard.
          </p>
        </div>
        <div className="banner-status">
          <span className="status-badge status-badge-accent">
            {selectedWorkbook?.status ?? "waiting"}
          </span>
          <strong>{selectedResult?.rows.length ?? 0} daily records</strong>
        </div>
      </section>

      {summaryCards.map((card) => (
        <section className="metric-card panel span-3" key={card.label}>
          <p className="metric-label">{card.label}</p>
          <strong className="metric-value">{card.value}</strong>
          <p className="metric-detail">{card.detail}</p>
          <SparklineChart tone={card.tone} values={card.series} />
        </section>
      ))}

      <section className="panel insight-panel span-4">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">Access Context</p>
            <h3>Current User</h3>
          </div>
          <span className="status-badge">client</span>
        </div>
        {error ? <p className="error-text">{error}</p> : null}
        {summary ? (
          <div className="detail-list">
            <div>
              <span>Name</span>
              <strong>{summary.user.full_name}</strong>
            </div>
            <div>
              <span>Email</span>
              <strong>{summary.user.email}</strong>
            </div>
            <div>
              <span>Roles</span>
              <strong>{summary.user.role_codes.join(", ")}</strong>
            </div>
          </div>
        ) : (
          <p className="muted">Loading client summary...</p>
        )}
      </section>

      <section className="panel insight-panel span-4">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">Service Capabilities</p>
            <h3>Planned Delivery</h3>
          </div>
        </div>
        <ul className="insight-list">
          {(summary?.capabilities ?? []).map((capability) => (
            <li key={capability}>{capability}</li>
          ))}
        </ul>
      </section>

      <section className="panel insight-panel span-4">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">Selected Workbook</p>
            <h3>Result Focus</h3>
          </div>
          <span className="status-badge">{selectedWorkbook?.status ?? "empty"}</span>
        </div>
        <div className="detail-list">
          <div>
            <span>File</span>
            <strong>{selectedWorkbook?.file_name ?? "No workbook selected"}</strong>
          </div>
          <div>
            <span>Month</span>
            <strong>{selectedWorkbook?.workbook_month ?? "unknown"}</strong>
          </div>
          <div>
            <span>Last Balance</span>
            <strong>
              {latestRow
                ? latestRow.tneb_balance.toLocaleString(undefined, {
                    maximumFractionDigits: 2,
                    minimumFractionDigits: 2,
                  })
                : "0.00"}
            </strong>
          </div>
        </div>
      </section>

      <div className="span-12">
        <UploadWorkbookPanel
          onUploaded={(workbookId) => {
            const session = getStoredSession();
            if (!session) {
              return;
            }
            fetchWorkbookHistory(session.token).then((items) => {
              setWorkbooks(items);
              setSelectedWorkbookId(workbookId);
            });
          }}
        />
      </div>

      <div className="span-5">
        <WorkbookHistoryPanel
          items={workbooks}
          onSelect={setSelectedWorkbookId}
          selectedWorkbookId={selectedWorkbookId}
        />
      </div>

      <div className="span-7">
        <SolarWorkingResultsPanel
          error={resultError}
          isLoading={isLoadingResults}
          result={selectedResult}
        />
      </div>
    </DashboardShell>
  );
}
